<?php

drupal_add_css(drupal_get_path('module', 'actorscenter_lottery') . '/actorscenter_lottery.css', array('group' => CSS_DEFAULT, 'type' => 'file'));

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function actorscenter_lottery_help($path, $arg) {
  switch ($path) {
    case "admin/help#actorscenter_lottery":
      return '<p>' . t("Content types and other code for AC's Lottery auditions") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function actorscenter_lottery_menu() {
  $items = array();

/*
  $items['admin/config/content/actorscenter_lottery'] = array(
    'title' => 'Imagefield Exact Dimensions',
    'description' => 'Allow a content type to require one of a list of exact image dimensions in Image fields.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('actorscenter_lottery_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  */
  $items['lottery_signup'] = array(
    'title' => 'Lottery Audition Signups',
    'description' => 'Sign up for pending lottery auditions.',
    'page callback' => 'lottery_audition_signup_page',
    'access callback' => 'user_is_logged_in', // XXX should have a callback that checks against a configured list of roles to do the thing... actually, define a permission and have site maintainers grant it to appropriate roles
  );

  return $items;
}

function lottery_audition_signup_page(){
  $lotteries = node_load_multiple(array(), array('type' => "lottery_audition"));
dpm($lotteries);
#XXX skip lotteries that've already happened
#XXX skip unpublished lotteries
#XXX if signups are closed but the auditions haven't happened, indicate that
#XXX if nothing meets above criteria, display a helpful message

  $output = array();
  $output['#markup'] = "";
  foreach ($lotteries as $nid => $lottery){
    $output['#markup'] .= drupal_render(drupal_get_form('lottery_signup_'.$nid, $nid, $lottery));
  }

  return $output;
}

function _actorscenter_lottery_form_builder($form, &$form_state, $args){
  $nid = $args[1];
  $lottery = $args[1];
  $form['lottery_signup_derp'] = array(
    '#type' => 'fieldset',
    '#title' => t($lottery->title),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    'submit' => array(
      '#type' => 'submit',
      '#value' => t($lottery->title),
    )
  );
# XXX time blocks: checkbox with a little clicky calendar style whoozit, should work interchangeably. THE COLORS, CHILDREN.
  return($form);
}

function actorscenter_lottery_forms($form_id, $args) {
  if(!preg_match("/^lottery_signup_\d+$/", $form_id) || count($args) != 2){
    return;
  }
  $nid = $args[0];
  $lottery = $args[1];

  $forms['lottery_signup_'.$nid] = array(
    'callback' => '_actorscenter_lottery_form_builder',
    'callback arguments' => array($args)
  );
  return $forms;
}

/*
function actorscenter_lottery_theme($existing, $type, $theme, $path) {
}
*/

/*
function actorscenter_lottery_block_info() {
  $blocks['lottery_audition_signup'] = array(
    'info' => t('Lottery Audition Signups'),
    'cache' => DRUPAL_CACHE_PER_USER,
  );
  return $blocks;
}
*/

function actorscenter_lottery_field_widget_form_alter(&$element, &$form_state, $context) {
  // Add custom validation hooks for Field Collections. Horrible.
  if ($context['field']['field_name'] == 'field_lottery_time_blocks') {
    array_unshift($element['#element_validate'], 'actorscenter_lottery_field_lottery_time_blocks_validate');
    $new_tr_validate = array(); // XXX strip out date_combo_validate and call explicitly from our own callback, *after* we've fudged the values
    foreach ($element['field_time_range'][LANGUAGE_NONE][0]['#element_validate'] as $callback){
      if($callback != "date_combo_validate"){
	$new_tr_validate[] = $callback;
      }
    }
    $element['field_time_range'][LANGUAGE_NONE][0]['#element_validate'] = $new_tr_validate;
  }
}

/**
 * Make sure the ends of our audition time blocks are on the same days as their
 * respective beginnings (really we're just collecting the time bit).
 * 
 * It seems we have to account for Date fields being stored in any number of
 * formats (flat strftime()-style strings, arrays of strings representing
 * date and time separately, or DateTime objects). Whoever wrote this crap is
 * the first one up against the wall when the revolution comes.
 */
function _actorscenter_lottery_datefield_sync_dates(&$datefield){
  $date1 = "";
  if(is_object($datefield['value'])){
    $date1 = strtotime($datefield['value']);
  } elseif(is_array($datefield['value'])){
    $date1 = strtotime($datefield['value']['date']);
  } else {
    $date1 = strtotime($datefield['value']);
//    $date1 = preg_replace("/\s.*/", "", $datefield['value'];
  }

  if(is_object($datefield['value2'])){
    $datefield['value2']->setDate(date('Y', $date1), date('m', $date1), date('d', $date1));
  } elseif(is_array($datefield['value2'])){
    $datefield['value2']['date'] = $datefield['value']['date'];
  } else {
    $date2 = strtotime($datefield['value2']);
    $datefield['value2'] = date('Y-m-d', $date1)." ".date('H:i:s', $date2);
  }
}

function actorscenter_lottery_field_lottery_time_blocks_validate($element, &$form_state, $form) {    
  $count = 0;
  drupal_add_css(drupal_get_path('module', 'actorscenter_lottery') . '/actorscenter_lottery.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
  while(array_key_exists($count, $form['field_lottery_time_blocks'][LANGUAGE_NONE])){
    // XXX This is the wrong way to do this, but form_set_value just doesn't
    // fucking work
    _actorscenter_lottery_datefield_sync_dates($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]);
    _actorscenter_lottery_datefield_sync_dates($form_state['input']['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]);

    if(array_key_exists("entity", $form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$count])){
      _actorscenter_lottery_datefield_sync_dates($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['entity']->field_time_range[LANGUAGE_NONE][0]);
    }


    $count++;
  }

  // Now it should be safe to invoke date_combo_validate
  _actorscenter_lottery_datefield_sync_dates($element['field_time_range'][LANGUAGE_NONE][0]['#value']);
  $element['field_time_range'][LANGUAGE_NONE][0]['value2']['#value']['date'] = $element['field_time_range'][LANGUAGE_NONE][0]['value']['#value']['date'];
  $element['field_time_range'][LANGUAGE_NONE][0]['value2']['date']['#value'] = $element['field_time_range'][LANGUAGE_NONE][0]['value']['date']['#value'];
  date_combo_validate($element['field_time_range'][LANGUAGE_NONE][0], $form_state);

}

/**
 * Implements hook_form_alter().
 */
function actorscenter_lottery_form_alter(&$form, $form_state, $form_id) {
  if($form_id == "lottery_audition_node_form"){
    drupal_add_css(drupal_get_path('module', 'actorscenter_lottery') . '/actorscenter_lottery.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
    drupal_add_js(drupal_get_path('module', 'actorscenter_lottery') . '/actorscenter_lottery.js');

    array_unshift($form['#validate'], 'actorscenter_lottery_form_validate');
    $form['wrapper'] = array(
      '#prefix' => '<div id="lottery_form_wrapper">',
      '#suffix' => '</div>'
    );
    $form['field_lottery_time_blocks']['wrapper'] = array(
      '#prefix' => '<div id="lottery_time_block">',
      '#suffix' => '</div>',
    );
    $count = 0;
    while(array_key_exists($count, $form['field_lottery_time_blocks'][LANGUAGE_NONE])){
      /*
      $form['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]['#ajax'] = array(
	'event' => 'change',
        'callback' => '_actorscenter_lottery_timeblock_ajax',
        'wrapper' => 'lottery_block_timerange_'.$count
      );
      */
      $count++;
    }
  }
}

function _actorscenter_lottery_timeblock_ajax(&$form, $form_state){
  /*
  $commands = array();
  $count = 0;
  while(array_key_exists($count, $form['field_lottery_time_blocks'][LANGUAGE_NONE])){
  }
  */

  return($form['field_lottery_time_blocks']['wrapper']);
}

/**
 */
/*
function actorscenter_lottery_form_submit($form, &$form_state){
}
*/

/**
 * Implements validation from the Form API.
 * 
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state 
 *   during processing.
 */
function actorscenter_lottery_form_validate($form, &$form_state){
  $count = 0;

  while(array_key_exists($count, $form['field_lottery_time_blocks'][LANGUAGE_NONE])){
    $css_id = "#lottery_block_timerange_$count";
    if(!isset($form['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]['#value'])){
      break;
    }
    $form_elt = "field_lottery_time_blocks][".LANGUAGE_NONE."][$count][field_time_range][und";

    $start = strtotime($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]['value']);
    $end = strtotime($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$count]['field_time_range'][LANGUAGE_NONE][0]['value2']);

    if(($end - $start)/3600 > 12){
      form_set_error($form_elt, "Time blocks cannot span more than 12 hours");
    } elseif(($end - $start) < 900) {
      form_set_error($form_elt, "Time blocks must be 15 minutes or longer");
    }
    $subcount = 0;
    while(array_key_exists($subcount, $form['field_lottery_time_blocks'][LANGUAGE_NONE])){
      if($count == $subcount){
	$subcount++;
	continue;
      }
      $substart = strtotime($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$subcount]['field_time_range'][LANGUAGE_NONE][0]['value']);
      $subend = strtotime($form_state['values']['field_lottery_time_blocks'][LANGUAGE_NONE][$subcount]['field_time_range'][LANGUAGE_NONE][0]['value2']);
      $form_subelt = "field_lottery_time_blocks][".LANGUAGE_NONE."][$subcount][field_time_range][und";
      if (($substart >= $start && $substart <= $end) ||
	  ($subend >= $start && $subend <= $end)){
	form_set_error($form_subelt, "Audition time block ".date('Y-m-d H:i:s', $substart)." - ".date('Y-m-d H:i:s', $subend)." overlaps with another block");
      }
      $subcount++;
    }

    $count++;
  }
}


/**
 * Implements hook_theme_registry_alter().
 */
function actorscenter_lottery_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'actorscenter_lottery')."/templates";
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
